# Purpose: extract organization seeds by continent using country (P17) -> continent (P30).
# Fields: item, itemLabel, continent, continentLabel, creation_date P571, dissolution_date P576, country P17, located_in P276, parent_organization P749, instance_of P31, industry P452.
# Expected result order: 1e5-1e6 rows on the public Wikidata endpoint.
# License: Wikidata data is CC0.
SELECT DISTINCT ?item ?itemLabel ?continent ?continentLabel ?creation_date ?dissolution_date ?country ?countryLabel ?located_in ?located_inLabel ?parent_organization ?parent_organizationLabel ?instance_of ?instance_ofLabel ?industry ?industryLabel WHERE {
  VALUES ?continent { wd:Q15 wd:Q46 wd:Q48 wd:Q49 wd:Q51 wd:Q538 wd:Q5401 }
  ?item wdt:P31/wdt:P279* wd:Q43229;
    wdt:P17 ?country.
  ?country wdt:P30 ?continent.
  OPTIONAL { ?item wdt:P571 ?creation_date. }
  OPTIONAL { ?item wdt:P576 ?dissolution_date. }
  OPTIONAL { ?item wdt:P276 ?located_in. }
  OPTIONAL { ?item wdt:P749 ?parent_organization. }
  OPTIONAL { ?item wdt:P31 ?instance_of. }
  OPTIONAL { ?item wdt:P452 ?industry. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,ja". }
}
ORDER BY ?continent ?item
LIMIT 5000
OFFSET 0

