-- Public subset query set generated by etl/26_license_audit.py.
-- It keeps only organizations whose full traced source dependency set is
-- public_redistributable. Run each SELECT into a table when constructing
-- a subset SQLite database.


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT o.*
FROM organization o
JOIN public_organizations po ON po.organization_id = o.organization_id;


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT DISTINCT s.*
FROM source s
JOIN ranked_dependencies rd ON rd.source_id = s.source_id
JOIN public_organizations po ON po.organization_id = rd.organization_id
WHERE s.redistribution = 'public_redistributable';


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT DISTINCT c.*
FROM claim c
JOIN source s ON s.source_id = c.source_id
WHERE s.redistribution = 'public_redistributable'
  AND (
    (c.entity_type = 'organization'
      AND c.entity_id IN (SELECT organization_id FROM public_organizations))
    OR EXISTS (
      SELECT 1 FROM organization_form_assignment x
      WHERE (x.claim_id = c.claim_id
          OR (x.assignment_id = c.entity_id
          AND c.entity_type = 'organization_form_assignment'))
        AND x.organization_id IN (SELECT organization_id FROM public_organizations)
    )
    OR EXISTS (
      SELECT 1 FROM relation x
      WHERE (x.claim_id = c.claim_id
          OR (x.relation_id = c.entity_id
          AND c.entity_type = 'relation'))
        AND x.source_organization_id IN (SELECT organization_id FROM public_organizations)
        AND x.target_organization_id IN (SELECT organization_id FROM public_organizations)
    )
    OR EXISTS (
      SELECT 1 FROM organization_temporal_facet x
      WHERE (x.claim_id = c.claim_id
          OR (x.organization_facet_id = c.entity_id
          AND c.entity_type = 'organization_temporal_facet'))
        AND x.organization_id IN (SELECT organization_id FROM public_organizations)
    )
    OR EXISTS (
      SELECT 1 FROM event x
      JOIN event_organization eo ON eo.event_id = x.event_id
      WHERE (x.claim_id = c.claim_id
          OR (x.event_id = c.entity_id
          AND c.entity_type = 'event'))
        AND eo.organization_id IN (SELECT organization_id FROM public_organizations)
    )
    OR EXISTS (
      SELECT 1 FROM activity x
      WHERE (x.claim_id = c.claim_id
          OR (x.activity_id = c.entity_id
          AND c.entity_type = 'activity'))
        AND x.organization_id IN (SELECT organization_id FROM public_organizations)
    )
    OR EXISTS (
      SELECT 1 FROM impact_record x
      WHERE (x.claim_id = c.claim_id
          OR (x.impact_id = c.entity_id
          AND c.entity_type = 'impact_record'))
        AND x.organization_id IN (SELECT organization_id FROM public_organizations)
    )
    OR EXISTS (
      SELECT 1 FROM function_record x
      WHERE (x.claim_id = c.claim_id
          OR (x.function_id = c.entity_id
          AND c.entity_type = 'function_record'))
        AND x.organization_id IN (SELECT organization_id FROM public_organizations)
    )
  );


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT ofa.*
FROM organization_form_assignment ofa
JOIN public_organizations po ON po.organization_id = ofa.organization_id;


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT r.*
FROM relation r
JOIN public_organizations spo ON spo.organization_id = r.source_organization_id
JOIN public_organizations tpo ON tpo.organization_id = r.target_organization_id;


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT e.*
FROM event e
WHERE EXISTS (
  SELECT 1
  FROM event_organization eo
  JOIN public_organizations po ON po.organization_id = eo.organization_id
  WHERE eo.event_id = e.event_id
);


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT eo.*
FROM event_organization eo
JOIN public_organizations po ON po.organization_id = eo.organization_id;


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT a.*
FROM activity a
JOIN public_organizations po ON po.organization_id = a.organization_id;


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT fr.*
FROM function_record fr
JOIN public_organizations po ON po.organization_id = fr.organization_id;


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT ir.*
FROM impact_record ir
JOIN public_organizations po ON po.organization_id = ir.organization_id;


WITH org_source_dependencies AS (
  SELECT c.entity_id AS organization_id, c.source_id, 'organization' AS dependency_path
  FROM claim c
  JOIN organization o ON o.organization_id = c.entity_id
  WHERE c.entity_type = 'organization' AND c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c ON c.claim_id = ofa.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ofa.organization_id, c.source_id, 'organization_form_assignment' AS dependency_path
  FROM organization_form_assignment ofa
  JOIN claim c
    ON c.entity_type = 'organization_form_assignment'
   AND c.entity_id = ofa.assignment_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.claim_id = r.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.source_organization_id AS organization_id, c.source_id, 'relation_source' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT r.target_organization_id AS organization_id, c.source_id, 'relation_target' AS dependency_path
  FROM relation r
  JOIN claim c ON c.entity_type = 'relation' AND c.entity_id = r.relation_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c ON c.claim_id = otf.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT otf.organization_id, c.source_id, 'organization_temporal_facet' AS dependency_path
  FROM organization_temporal_facet otf
  JOIN claim c
    ON c.entity_type = 'organization_temporal_facet'
   AND c.entity_id = otf.organization_facet_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.claim_id = e.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT eo.organization_id, c.source_id, 'event' AS dependency_path
  FROM event e
  JOIN event_organization eo ON eo.event_id = e.event_id
  JOIN claim c ON c.entity_type = 'event' AND c.entity_id = e.event_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.claim_id = a.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT a.organization_id, c.source_id, 'activity' AS dependency_path
  FROM activity a
  JOIN claim c ON c.entity_type = 'activity' AND c.entity_id = a.activity_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.claim_id = ir.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT ir.organization_id, c.source_id, 'impact_record' AS dependency_path
  FROM impact_record ir
  JOIN claim c ON c.entity_type = 'impact_record' AND c.entity_id = ir.impact_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.claim_id = fr.claim_id
  WHERE c.source_id IS NOT NULL

  UNION
  SELECT fr.organization_id, c.source_id, 'function_record' AS dependency_path
  FROM function_record fr
  JOIN claim c ON c.entity_type = 'function_record' AND c.entity_id = fr.function_id
  WHERE c.source_id IS NOT NULL
),
ranked_dependencies AS (
  SELECT
    d.organization_id,
    d.source_id,
    d.dependency_path,
    s.title,
    s.source_type,
    s.license,
    s.redistribution,
    CASE s.redistribution
      WHEN 'public_redistributable' THEN 1
      WHEN 'attribution_required' THEN 2
      WHEN 'noncommercial' THEN 3
      WHEN 'private' THEN 4
      WHEN 'restricted' THEN 5
      ELSE 6
    END AS restriction_rank
  FROM org_source_dependencies d
  JOIN source s ON s.source_id = d.source_id
),
organization_license AS (
  SELECT
    o.organization_id,
    o.canonical_name,
    COUNT(DISTINCT rd.source_id) AS source_count,
    COALESCE(MAX(rd.restriction_rank), 6) AS max_restriction_rank,
    CASE COALESCE(MAX(rd.restriction_rank), 6)
      WHEN 1 THEN 'public_redistributable'
      WHEN 2 THEN 'attribution_required'
      WHEN 3 THEN 'noncommercial'
      WHEN 4 THEN 'private'
      WHEN 5 THEN 'restricted'
      ELSE 'unclassified'
    END AS max_redistribution
  FROM organization o
  LEFT JOIN ranked_dependencies rd ON rd.organization_id = o.organization_id
  GROUP BY o.organization_id, o.canonical_name
),
organization_most_restrictive_source AS (
  SELECT organization_id, source_id, title, redistribution, restriction_rank
  FROM (
    SELECT
      rd.*,
      ROW_NUMBER() OVER (
        PARTITION BY rd.organization_id
        ORDER BY rd.restriction_rank DESC, rd.title, rd.source_id
      ) AS row_num
    FROM ranked_dependencies rd
  )
  WHERE row_num = 1
),
public_organizations AS (
  SELECT organization_id
  FROM organization_license
  WHERE source_count > 0 AND max_restriction_rank = 1
)

SELECT otf.*
FROM organization_temporal_facet otf
JOIN public_organizations po ON po.organization_id = otf.organization_id;
